#!/usr/bin/env bash
# print Best School 10 time and hi in the line 9

i=1

while [ $i -le 10 ]
do
    if [ $i -ne 9 ]
    then
        echo "Best School"
    else
        echo "hi"
    fi
    ((i++))
done
