#!/usr/bin/env bash
# test multiple case in a loop

i=1

while [ $i -le 20 ]
do
    echo "$i"

    case $i in
        "4") echo "bad luck from China";;
        "8") echo "bad luck from Japan";;
        "17") echo "bad luck from Italy";;
    esac
    (( i++ ))
done
