#!/usr/bin/env bash
# display a clock

hours=0
minutes=1

echo "Hour: $hours"
while [ $hours -le 12 ]
do
  while [ $minutes -le 59 ]
  do
    echo "$minutes"
    (( minutes++ ))
    if [ $minutes -eq 59 ]
    then
      (( hours++ ))
    fi
  done
  echo "Hour: $hours"
  minutes=0
done
